### ISSUE TITLE
Composer: doesn't work when repo has named differently than the package

### ISSUE THREAD

**Issue by fprochazka** [OctoLinker/browser-extension#36] opened 2015-07-06 22:00 UTC
For example the `doctrine/orm` in https://github.com/Kdyby/Doctrine/blob/master/composer.json is not linked.

**Comment by stefanbuck** [comment] 2015-07-07 05:46
Thanks for reporting. The issue is the new line after `nette/robot-loader`. Not sure how I can fix that at the moment. 

I'm thinking about doing a bigger refactoring of the core. This would be ideally less strict with the dom .. we will see :wink:

**Comment by stefanbuck** [comment] 2016-05-12 04:58
Fixed in latest version

**Closed by stefanbuck** 2016-05-12 04:58 UTC
Labels: bug

**Comment by fprochazka** [comment] 2016-05-12 08:44
Thanks!
