### ISSUE TITLE
Superfluous '.' introduced

### ISSUE THREAD

**Issue by silverwind** [OctoLinker/browser-extension#350] opened 2017-04-24 20:22 UTC
**Browser name:** Firefox
**Browser version:** 54
**OctoLinker version:** 4.8.0
**URL and line number where issue occurs:** https://github.com/silverwind/oui/commit/03504e482f50b0c9243123ed9e222b4981ae01ff#diff-2fbe63f0ca81ccc1151eb979b3ff1270L76
**Expected behavior:** `require(".").search`
**Actual behavior:** `require(".")..search` (note the extra '.')

<img width="596" src="https://cloud.githubusercontent.com/assets/115237/25356968/7e8b5746-293c-11e7-9219-5d9ddac0f71d.png">

**Comment by josephfrazier** [comment] 2017-04-24 21:44
Thanks for the report, @silverwind! I was able to reproduce the issue with OctoLinker 4.8.0, but not with [v4.10.0](https://github.com/OctoLinker/browser-extension/commit/1e7ff6fdf34592a2e4b16f03e60a2b3551eceddd), using the [firefox-open](https://github.com/OctoLinker/browser-extension/blob/5bf99a86dfd163a8e22bc1c0b0f2ca491eb76338/package.json#L26) script in package.json. However, v4.10.0 hasn't been released for Firefox yet, due to https://github.com/OctoLinker/browser-extension/issues/351, so I think we should close this issue in favor of that one.

**Comment by josephfrazier** [comment] 2017-04-24 23:36
Note that you can use [Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) to install the addon in Firefox from the [Chrome Store](https://chrome.google.com/webstore/detail/octolinker/jlmafbaeoofdegohdhinkhilhclaklkp).

**Comment by josephfrazier** [comment] 2017-04-25 18:24
OctoLinker v4.11.0 has been released with the fix and is now available from Mozilla: https://addons.mozilla.org/en-US/firefox/addon/octolinker/versions/?page=1#version-4.11.0

**Closed by josephfrazier** 2017-04-25 18:24 UTC

**Comment by silverwind** [comment] 2017-04-26 03:21
Fix confirmed, thanks!
